# triggered by schedule (not in yml)
trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -e
    npm run bump-version && npx vsce publish $f --pat "$(marketplace_key)" --noVerify
  displayName: 'Publish to marketplace'