# triggered by schedule (not in yml)
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -e
    chmod +x ./build/bumpAndPublish.sh
    ./build/bumpAndPublish.sh "$(marketplace_key)"
  displayName: 'Publish to marketplace'