# triggered by schedule (not in yml)
trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -e
    chmod +x ./build/bumpAndPublish.sh
    ./build/bumpAndPublish.sh
  displayName: 'Publish to marketplace'